version: "3.9"
services:
  backend:
    build:
      context: ./Curriculo-store.Server
      dockerfile: Dockerfile
    ports:
      - "5000:80"



  frontend:
    build:
      context: ./curriculo-store.client
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
