version: "3.9"
services:
  backend:
    build:
      context: ./Curriculo-store.Server
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - ./Curriculo-store.Server:/app



  frontend:
    build:
      context: ./curriculo-store.client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./curriculo-store.client:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
